import {readFileSync} from 'node:fs';
import {YooKassaReader} from './yookassa.mjs';
export function paymentUrl(value){const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password||!['yoomoney.ru','yookassa.ru'].some(h=>u.hostname===h||u.hostname.endsWith('.'+h)))throw new Error('Unexpected payment page');return u.href;}
export class Billing {
 constructor(store,{shopId,secret,testMode=false,receipt=true,vatCode=1,taxSystemCode=null,paymentMode='full_prepayment',request=fetch}={}){
  this.store=store;this.request=request;this.config={shopId,secret,testMode,receipt,vatCode,taxSystemCode,paymentMode};
  this.reader=shopId&&secret?new YooKassaReader({shopId,secret,testMode,request}):null;
  for(const [name,type] of [['confirmation_url','TEXT'],['receipt_email','TEXT'],['checked_at','INTEGER NOT NULL DEFAULT 0'],['refund_request','TEXT'],['refund_id','TEXT'],['refund_requested_at','INTEGER']])if(!store.db.prepare('PRAGMA table_info(orders)').all().some(x=>x.name===name))store.db.exec(`ALTER TABLE orders ADD COLUMN ${name} ${type}`);
 }
 ready(){const c=this.config;return Boolean(this.reader&&(!c.receipt||Number.isInteger(c.vatCode)&&c.vatCode>=1&&c.vatCode<=12)&&['full_payment','full_prepayment'].includes(c.paymentMode));}
 async checkout(accountId,days,key,email){
  if(!this.ready())throw new Error('Оплата временно недоступна');
  if(typeof email!=='string'||email.length>254||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error('Укажи email для чека');
  const order=this.store.createOrder(accountId,days,key);
  if(order.state!=='pending')throw new Error('Заказ уже завершён');
  if(order.receipt_email&&order.receipt_email!==email)throw new Error('Данные заказа уже сохранены');
  if(order.confirmation_url)return {orderId:order.id,url:paymentUrl(order.confirmation_url)};
  // The provider retains idempotence keys for24h; never retry an ambiguous old creation.
  if(this.store.clock()-order.created_at>23*3600_000)throw new Error('Заказ устарел. Создай новый');
  this.store.db.prepare('UPDATE orders SET receipt_email=? WHERE id=?').run(email,order.id);
  const c=this.config,amount={value:(order.price_minor/100).toFixed(2),currency:'RUB'},description=`Family VPN — ${order.days} дней`;
  const payload={amount,capture:true,description,metadata:{product:'family-vpn',order_id:order.id},confirmation:{type:'redirect',return_url:'https://family-pie.ru/vpn/cabinet/#plans?order='+order.id}};
  if(c.receipt){payload.receipt={customer:{email},items:[{description,quantity:'1.00',amount,vat_code:c.vatCode,payment_subject:'service',payment_mode:c.paymentMode}]};if(c.taxSystemCode)payload.receipt.tax_system_code=c.taxSystemCode;}
  const response=await this.request('https://api.yookassa.ru/v3/payments',{method:'POST',headers:{Authorization:`Basic ${Buffer.from(c.shopId+':'+c.secret).toString('base64')}`,'Content-Type':'application/json','Idempotence-Key':order.id},body:JSON.stringify(payload),signal:AbortSignal.timeout(12000),redirect:'error'});
  if(!response.ok)throw new Error('Не удалось создать платёж. Повтори позже');
  const payment=await response.json();if(typeof payment.id!=='string'||!/^[A-Za-z0-9-]{1,128}$/.test(payment.id))throw new Error('Invalid provider object');
  const url=paymentUrl(payment.confirmation?.confirmation_url);this.store.bindPayment(accountId,order.id,payment.id);this.store.db.prepare('UPDATE orders SET confirmation_url=? WHERE id=?').run(url,order.id);
  return {orderId:order.id,url};
 }
 async check(accountId,id){const o=this.store.order(accountId,id);if(o.payment_id&&o.state==='pending')await this.confirm(o.payment_id);return this.store.order(accountId,id);}
 async confirm(id){const o=this.store.db.prepare('SELECT id FROM orders WHERE payment_id=?').get(id);if(!o)return false;const p=await this.reader.object('payments',id);if(p.metadata?.product!=='family-vpn'||p.metadata?.order_id!==o.id)throw new Error('Wrong product');if(p.status==='succeeded')this.store.confirmPayment(p,{testMode:this.config.testMode});else if(p.status==='canceled')this.store.db.prepare("UPDATE orders SET state='canceled' WHERE payment_id=? AND state='pending'").run(id);return true;}
 async webhook(event,id){if(!this.ready())throw new Error('Provider unavailable');if(event==='payment.succeeded'||event==='payment.canceled')return this.confirm(id);if(event==='refund.succeeded'){
  const refund=await this.reader.object('refunds',id),o=this.store.db.prepare('SELECT id FROM orders WHERE payment_id=?').get(refund.payment_id);if(!o)return false;const p=await this.reader.object('payments',refund.payment_id);if(p.metadata?.product!=='family-vpn'||p.metadata?.order_id!==o.id)throw new Error('Wrong product');await this.reader.confirmRefund(this.store,id);return true;
 }return false;}
 async refund(accountId,id,requestKey){const o=this.store.order(accountId,id);if(!this.ready()||o.state!=='paid')throw new Error('Оплаченный заказ не найден');if(!o.refund_request){if(typeof requestKey!=='string'||!/^[a-f0-9-]{36}$/.test(requestKey))throw new Error('Invalid refund request');this.store.db.prepare('UPDATE orders SET refund_request=?,refund_requested_at=? WHERE id=? AND refund_request IS NULL').run(requestKey,this.store.clock(),id);}const current=this.store.order(accountId,id);if(current.refund_id){await this.reader.confirmRefund(this.store,current.refund_id);return {id:current.refund_id};}if(this.store.clock()-current.refund_requested_at>23*3600_000)throw new Error('Проверь неоднозначный возврат в ЮKassa перед повтором');const payload={payment_id:o.payment_id,amount:{currency:'RUB',value:(o.price_minor/100).toFixed(2)}};if(this.config.receipt){payload.receipt={customer:{email:o.receipt_email},items:[{description:`Family VPN — ${o.days} дней`,quantity:'1.00',amount:payload.amount,vat_code:this.config.vatCode,payment_subject:'service',payment_mode:this.config.paymentMode}]};if(this.config.taxSystemCode)payload.receipt.tax_system_code=this.config.taxSystemCode;}const response=await this.request('https://api.yookassa.ru/v3/refunds',{method:'POST',headers:{Authorization:`Basic ${Buffer.from(this.config.shopId+':'+this.config.secret).toString('base64')}`,'Content-Type':'application/json','Idempotence-Key':current.refund_request},body:JSON.stringify(payload),signal:AbortSignal.timeout(12000),redirect:'error'});if(!response.ok)throw new Error('Возврат не создан. Проверь статус в ЮKassa');const r=await response.json();if(typeof r.id!=='string'||!/^[A-Za-z0-9-]{1,128}$/.test(r.id))throw new Error('Invalid refund object');this.store.db.prepare('UPDATE orders SET refund_id=? WHERE id=?').run(r.id,id);await this.reader.confirmRefund(this.store,r.id);return {id:r.id};}
 async reconcile(){if(!this.ready())return;for(const o of this.store.db.prepare("SELECT id,payment_id,refund_id FROM orders WHERE payment_id IS NOT NULL AND (state='pending' OR state='paid' AND refund_id IS NOT NULL) ORDER BY checked_at LIMIT 10").all()){this.store.db.prepare('UPDATE orders SET checked_at=? WHERE id=?').run(this.store.clock(),o.id);try{if(o.refund_id)await this.reader.confirmRefund(this.store,o.refund_id);else await this.confirm(o.payment_id);}catch{/* Next cycle retries; provider data and secrets never logged. */}}}
}
export function billingConfig(env=process.env){let secret='';if(env.VPN_YOOKASSA_SECRET_FILE)secret=readFileSync(env.VPN_YOOKASSA_SECRET_FILE,'utf8').trim();return {shopId:env.VPN_YOOKASSA_SHOP_ID,secret,testMode:env.VPN_YOOKASSA_TEST==='1',receipt:env.VPN_BILLING_RECEIPT!=='0',vatCode:Number(env.VPN_BILLING_VAT_CODE||1),taxSystemCode:env.VPN_BILLING_TAX_SYSTEM_CODE?Number(env.VPN_BILLING_TAX_SYSTEM_CODE):null,paymentMode:env.VPN_BILLING_PAYMENT_MODE||'full_prepayment'};}
