import {randomUUID,randomBytes} from 'node:crypto';
const text=(v,max)=>{if(typeof v!=='string'||!v.trim()||v.length>max)throw new Error('Проверь текст');return v.trim();};
export class Cabinet {
 constructor(store){this.store=store;this.db=store.db;this.db.exec(`
 CREATE TABLE IF NOT EXISTS cabinet_profiles(account_id TEXT PRIMARY KEY REFERENCES identities(account_id),display_name TEXT NOT NULL DEFAULT '',receipt_email TEXT NOT NULL DEFAULT '',news INTEGER NOT NULL DEFAULT 1,invite_code TEXT UNIQUE NOT NULL,inviter TEXT REFERENCES identities(account_id));
 CREATE TABLE IF NOT EXISTS cabinet_config(key TEXT PRIMARY KEY,value TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS support_threads(id TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES identities(account_id),subject TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS support_messages(id TEXT PRIMARY KEY,thread_id TEXT NOT NULL REFERENCES support_threads(id),author TEXT NOT NULL REFERENCES identities(account_id),body TEXT NOT NULL,created_at INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS support_files(id TEXT PRIMARY KEY,message_id TEXT NOT NULL REFERENCES support_messages(id),name TEXT NOT NULL,mime TEXT NOT NULL,data BLOB NOT NULL);
 CREATE TABLE IF NOT EXISTS news_posts(id TEXT PRIMARY KEY,title TEXT NOT NULL,body TEXT NOT NULL,published INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS news_reads(account_id TEXT NOT NULL REFERENCES identities(account_id),post_id TEXT NOT NULL REFERENCES news_posts(id),updated_at INTEGER NOT NULL,PRIMARY KEY(account_id,post_id));
 CREATE TABLE IF NOT EXISTS promo_codes(code TEXT PRIMARY KEY,percent INTEGER NOT NULL,max_uses INTEGER NOT NULL,expires INTEGER NOT NULL,enabled INTEGER NOT NULL DEFAULT 1);
 CREATE TABLE IF NOT EXISTS withdrawals(id TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES identities(account_id),amount INTEGER NOT NULL,state TEXT NOT NULL DEFAULT 'pending',created_at INTEGER NOT NULL,proof TEXT);
 `);for(const[name,type]of [['promo_code','TEXT'],['original_price_minor','INTEGER'],['referral_owner','TEXT'],['referral_reward_bp','INTEGER NOT NULL DEFAULT 0'],['referral_discount','INTEGER NOT NULL DEFAULT 0']])if(!this.db.prepare('PRAGMA table_info(orders)').all().some(x=>x.name===name))this.db.exec(`ALTER TABLE orders ADD COLUMN ${name} ${type}`);
 for(const table of ['support_threads','support_messages'])if(!this.db.prepare(`PRAGMA table_info(${table})`).all().some(x=>x.name==='request_key'))this.db.exec(`ALTER TABLE ${table} ADD COLUMN request_key TEXT`);
 this.db.exec('CREATE UNIQUE INDEX IF NOT EXISTS support_thread_requests ON support_threads(account_id,request_key);CREATE UNIQUE INDEX IF NOT EXISTS support_message_requests ON support_messages(author,request_key)');}
 profile(id){this.store.account(id);this.db.prepare('INSERT OR IGNORE INTO cabinet_profiles(account_id,invite_code) VALUES(?,?)').run(id,randomBytes(12).toString('base64url'));return this.db.prepare('SELECT display_name,receipt_email,news,invite_code FROM cabinet_profiles WHERE account_id=?').get(id);}
 updateProfile(id,p){this.profile(id);const old=this.profile(id),name=p.displayName??old.display_name,email=p.receiptEmail??old.receipt_email,news=p.news??Boolean(old.news);if(typeof name!=='string'||name.length>80||typeof email!=='string'||email.length>254||email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||typeof news!=='boolean')throw new Error('Проверь настройки');this.db.prepare('UPDATE cabinet_profiles SET display_name=?,receipt_email=?,news=? WHERE account_id=?').run(name.trim(),email.trim(),Number(news),id);return this.profile(id);}
 attribute(id,code){this.profile(id);if(!code)return;const inviter=this.db.prepare('SELECT account_id FROM cabinet_profiles WHERE invite_code=?').get(code);if(!inviter||inviter.account_id===id)return;this.db.prepare('UPDATE cabinet_profiles SET inviter=? WHERE account_id=? AND inviter IS NULL').run(inviter.account_id,id);}
 referralPolicy(){return JSON.parse(this.db.prepare("SELECT value FROM cabinet_config WHERE key='referrals'").get()?.value||'{"discount":0,"rewardBp":0,"withdrawMinimum":0}');}
 setReferralPolicy(p){if(!Number.isInteger(p.discount)||p.discount<0||p.discount>50||!Number.isInteger(p.rewardBp)||p.rewardBp<0||p.rewardBp>5000||!Number.isSafeInteger(p.withdrawMinimum)||p.withdrawMinimum<0||p.rewardBp>0&&p.withdrawMinimum<100)throw new Error('Проверь правила приглашений');p={discount:p.discount,rewardBp:p.rewardBp,withdrawMinimum:p.withdrawMinimum};this.db.prepare("INSERT INTO cabinet_config VALUES('referrals',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run(JSON.stringify(p));return p;}
 friends(id){const p=this.profile(id),policy=this.referralPolicy(),credits=this.db.prepare("SELECT id,price_minor,referral_reward_bp,created_at FROM orders WHERE referral_owner=? AND state='paid' ORDER BY created_at DESC").all(id).map(o=>({orderId:o.id,amount:Math.floor(o.price_minor*o.referral_reward_bp/10000),at:o.created_at})),reserved=this.db.prepare("SELECT coalesce(sum(amount),0) n FROM withdrawals WHERE account_id=? AND state IN ('pending','paid')").get(id).n;return {url:'https://family-pie.ru/vpn/cabinet/auth/?ref='+p.invite_code,registered:this.db.prepare('SELECT count(*) n FROM cabinet_profiles WHERE inviter=?').get(id).n,paid:this.db.prepare("SELECT count(DISTINCT p.account_id) n FROM cabinet_profiles p JOIN orders o USING(account_id) WHERE p.inviter=? AND o.state='paid'").get(id).n,rewardsEnabled:policy.rewardBp>0,policy,credits,balance:credits.reduce((sum,c)=>sum+c.amount,0)-reserved,withdrawals:this.db.prepare('SELECT id,amount,state,created_at FROM withdrawals WHERE account_id=? ORDER BY created_at DESC').all(id)};}
 withdraw(id,amount){return this.store.transaction(()=>{const f=this.friends(id);if(!f.rewardsEnabled||!Number.isSafeInteger(amount)||amount<f.policy.withdrawMinimum||amount>f.balance)throw new Error('Недостаточно доступных бонусов');const w=randomUUID();this.db.prepare("INSERT INTO withdrawals(id,account_id,amount,created_at) VALUES(?,?,?,?)").run(w,id,amount,this.store.clock());return {id:w};});}
 settleWithdrawal(actor,id,state,proof){if(!['paid','declined'].includes(state)||state==='paid'&&(!proof||typeof proof!=='string'||proof.length>200))throw new Error('Укажи подтверждение выполненного перевода');return this.store.transaction(()=>{const w=this.db.prepare("SELECT * FROM withdrawals WHERE id=? AND state='pending'").get(id);if(!w)throw new Error('Заявка не найдена');if(state==='paid'&&this.friends(w.account_id).balance<0)throw new Error('После возврата средств выплата недоступна');this.db.prepare('UPDATE withdrawals SET state=?,proof=? WHERE id=?').run(state,proof||null,id);this.db.prepare('INSERT INTO audit(actor,action,target,at) VALUES(?,?,?,?)').run(actor,'withdrawal.'+state,id,this.store.clock());});}
 plans(){return JSON.parse(this.db.prepare("SELECT value FROM cabinet_config WHERE key='plans'").get()?.value||'[]').map(p=>({...p,devices:0}));}
 setPlans(plans){if(!Array.isArray(plans)||plans.length>4||new Set(plans.map(p=>p.days)).size!==plans.length||plans.some(p=>![30,90,180,365].includes(p.days)||!Number.isSafeInteger(p.priceMinor)||p.priceMinor<100||p.priceMinor>100000000||!Number.isInteger(p.devices)||p.devices<0||p.devices>100))throw new Error('Проверь тарифы');plans=plans.map(({days,priceMinor})=>({days,priceMinor,devices:0}));this.db.prepare("INSERT INTO cabinet_config VALUES('plans',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run(JSON.stringify(plans));this.store.plans=new Map(plans.map(p=>[String(p.days),Object.freeze({...p})]));return plans;}
 promo(code){code=text(code,64).toUpperCase();const p=this.db.prepare('SELECT * FROM promo_codes WHERE code=? AND enabled=1 AND expires>?').get(code,this.store.clock());if(!p)throw new Error('Промокод не действует');return p;}
 setPromo(p){const code=text(p.code,64).toUpperCase();if(!/^[A-Z0-9_-]+$/.test(code)||!Number.isInteger(p.percent)||p.percent<1||p.percent>99||!Number.isInteger(p.maxUses)||p.maxUses<1||p.maxUses>100000||!Number.isSafeInteger(p.expires)||p.expires<=this.store.clock())throw new Error('Проверь промокод');this.db.prepare('INSERT INTO promo_codes VALUES(?,?,?,?,1) ON CONFLICT(code) DO UPDATE SET percent=excluded.percent,max_uses=excluded.max_uses,expires=excluded.expires,enabled=1').run(code,p.percent,p.maxUses,p.expires);return {code,percent:p.percent};}
 createOrder(id,days,key,code){return this.store.transaction(()=>{const old=this.db.prepare('SELECT id,promo_code FROM orders WHERE account_id=? AND request_key=?').get(id,key);if(old){if((code?.toUpperCase()||null)!==old.promo_code)throw new Error('Данные заказа уже сохранены');return this.store.createOrderInternal(id,days,key);}let promo;
  if(code){promo=this.promo(code);if(this.db.prepare("SELECT count(*) n FROM orders WHERE promo_code=? AND (state='paid' OR state='pending' AND created_at>?)").get(promo.code,this.store.clock()-3600_000).n>=promo.max_uses||this.db.prepare("SELECT 1 FROM orders WHERE account_id=? AND promo_code=? AND state='paid'").get(id,promo.code))throw new Error('Промокод уже использован');}
  const order=this.store.createOrderInternal(id,days,key),policy=this.referralPolicy(),inviter=this.db.prepare('SELECT inviter FROM cabinet_profiles WHERE account_id=?').get(id)?.inviter,first=inviter&&!this.db.prepare("SELECT 1 FROM orders WHERE account_id=? AND id<>? AND referral_discount>0 AND state IN ('pending','paid','refunded')").get(id,order.id);const discount=Math.max(promo?.percent||0,first?policy.discount:0),price=Math.max(100,Math.round(order.price_minor*(100-discount)/100));this.db.prepare('UPDATE orders SET original_price_minor=price_minor,price_minor=?,promo_code=?,referral_owner=?,referral_reward_bp=?,referral_discount=? WHERE id=?').run(price,promo?.code||null,inviter||null,inviter?policy.rewardBp:0,first?policy.discount:0,order.id);return this.store.order(id,order.id);});}
 orders(id){return this.db.prepare('SELECT id,days,price_minor,devices,state,created_at,promo_code FROM orders WHERE account_id=? ORDER BY created_at DESC LIMIT 100').all(id);}
 thread(id,owner,admin=false){const t=this.db.prepare('SELECT * FROM support_threads WHERE id=?').get(id);if(!t||!admin&&t.account_id!==owner)throw new Error('Обращение не найдено');return t;}
 threads(owner,admin=false){return this.db.prepare(`SELECT t.*,i.login FROM support_threads t JOIN identities i USING(account_id) ${admin?'':'WHERE t.account_id=?'} ORDER BY t.updated_at DESC LIMIT 100`).all(...admin?[]:[owner]);}
 messages(id,owner,admin=false){this.thread(id,owner,admin);return this.db.prepare('SELECT m.id,m.body,m.created_at,i.role FROM support_messages m JOIN identities i ON i.account_id=m.author WHERE m.thread_id=? ORDER BY m.created_at,m.rowid').all(id).map(m=>({...m,files:this.db.prepare('SELECT id,name,mime,length(data) size FROM support_files WHERE message_id=?').all(m.id)}));}
 createThread(owner,subject,body,key=null){subject=text(subject,120);body=text(body,5000);if(key){text(key,128);const old=this.db.prepare('SELECT * FROM support_threads WHERE account_id=? AND request_key=?').get(owner,key);if(old){if(old.subject!==subject||this.db.prepare('SELECT body FROM support_messages WHERE thread_id=? ORDER BY rowid LIMIT 1').get(old.id)?.body!==body)throw new Error('Данные обращения уже сохранены');return old;}}const count=this.db.prepare("SELECT count(*) n FROM support_threads WHERE account_id=? AND status='open'").get(owner).n;if(count>=10)throw new Error('Сначала дождись ответа по открытым обращениям');const id=randomUUID(),now=this.store.clock();return this.store.transaction(()=>{this.db.prepare('INSERT INTO support_threads(id,account_id,subject,status,created_at,updated_at,request_key) VALUES(?,?,?,\'open\',?,?,?)').run(id,owner,subject,now,now,key);this.reply(id,owner,body);return this.thread(id,owner);});}
 reply(id,owner,body,admin=false,key=null){const t=this.thread(id,owner,admin);body=text(body,5000);if(key){text(key,128);const old=this.db.prepare('SELECT * FROM support_messages WHERE author=? AND request_key=?').get(owner,key);if(old){if(old.thread_id!==id||old.body!==body)throw new Error('Сообщение уже сохранено с другим текстом');return {id:old.id};}}if(t.status==='closed')throw new Error('Обращение закрыто');const message=randomUUID(),now=this.store.clock();this.db.prepare('INSERT INTO support_messages(id,thread_id,author,body,created_at,request_key) VALUES(?,?,?,?,?,?)').run(message,id,owner,body,now,key);this.db.prepare('UPDATE support_threads SET updated_at=? WHERE id=?').run(now,id);return {id:message};}
 attachment(messageId,owner,name,mime,base64,admin=false){
  const m=this.db.prepare('SELECT * FROM support_messages WHERE id=?').get(messageId);
  if(!m||m.author!==owner)throw new Error('Сообщение не найдено');
  this.thread(m.thread_id,owner,admin);
  if(!['image/png','image/jpeg','image/webp','text/plain'].includes(mime)||typeof base64!=='string'||base64.length>1400000)throw new Error('Поддерживаются изображения или текст до1МБ');
  const data=Buffer.from(base64,'base64'),normalized=text(name,120).replace(/[\r\n/\\]/g,'_');
  if(!data.length||data.length>1048576)throw new Error('Файл слишком большой');
  const prior=this.db.prepare('SELECT id FROM support_files WHERE message_id=? AND name=? AND mime=? AND data=?').get(messageId,normalized,mime,data);
  if(prior)return {id:prior.id};
  const usage=this.db.prepare('SELECT count(*) n,coalesce(sum(length(data)),0) bytes FROM support_files f JOIN support_messages m ON m.id=f.message_id WHERE m.thread_id=?').get(m.thread_id);
  if(usage.n>=5||usage.bytes+data.length>5242880)throw new Error('Лимит вложений в обращении');
  const id=randomUUID();this.db.prepare('INSERT INTO support_files VALUES(?,?,?,?,?)').run(id,messageId,normalized,mime,data);return {id};
 }
 file(id,owner,admin=false){const f=this.db.prepare('SELECT f.*,m.thread_id FROM support_files f JOIN support_messages m ON m.id=f.message_id WHERE f.id=?').get(id);if(!f)throw new Error('Файл не найден');this.thread(f.thread_id,owner,admin);return f;}
 closeThread(id,owner,closed,admin=false){this.thread(id,owner,admin);if(typeof closed!=='boolean')throw new Error('Проверь статус');this.db.prepare('UPDATE support_threads SET status=?,updated_at=? WHERE id=?').run(closed?'closed':'open',this.store.clock(),id);}
 posts(id,admin=false){return this.db.prepare(`SELECT p.*,r.updated_at read_at FROM news_posts p LEFT JOIN news_reads r ON r.post_id=p.id AND r.account_id=? ${admin?'':'WHERE p.published=1'} ORDER BY p.created_at DESC LIMIT 100`).all(id);}
 savePost(p){const id=p.id||randomUUID(),now=this.store.clock();if(typeof p.published!=='boolean')throw new Error('Проверь публикацию');this.db.prepare('INSERT INTO news_posts VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,body=excluded.body,published=excluded.published,updated_at=excluded.updated_at').run(id,text(p.title,150),text(p.body,20000),Number(p.published),now,now);return {id};}
 readPost(id,post){const p=this.db.prepare('SELECT * FROM news_posts WHERE id=? AND published=1').get(post);if(!p)throw new Error('Новость не найдена');this.db.prepare('INSERT INTO news_reads VALUES(?,?,?) ON CONFLICT(account_id,post_id) DO UPDATE SET updated_at=excluded.updated_at').run(id,post,p.updated_at);}
}
