import {randomBytes,createPublicKey,verify,createHash} from 'node:crypto';
export class GoogleLogin{
 constructor(store,users,{clientId='',secret='',origin='https://family-pie.ru',request=fetch}={}){this.store=store;this.users=users;this.db=store.db;this.clientId=clientId;this.secret=secret;this.origin=origin;this.request=request;this.db.exec(`CREATE TABLE IF NOT EXISTS google_identities(subject TEXT PRIMARY KEY,account_id TEXT UNIQUE NOT NULL REFERENCES identities(account_id),email TEXT NOT NULL);CREATE TABLE IF NOT EXISTS google_states(id TEXT PRIMARY KEY,nonce TEXT NOT NULL,verifier TEXT NOT NULL,account_id TEXT,session_hash TEXT REFERENCES sessions(token_hash) ON DELETE CASCADE,expires INTEGER NOT NULL);`);}
 ready(){return Boolean(this.clientId&&this.secret);}
 start(session){if(!this.ready())throw new Error('Google ещё не подключён');this.db.prepare('DELETE FROM google_states WHERE expires<=?').run(this.store.clock());if(this.db.prepare('SELECT count(*) n FROM google_states').get().n>=1000)throw new Error('Повтори позже');const id=randomBytes(24).toString('base64url'),nonce=randomBytes(24).toString('base64url'),verifier=randomBytes(32).toString('base64url');this.db.prepare('INSERT INTO google_states VALUES(?,?,?,?,?,?)').run(id,nonce,verifier,session?.account_id||null,session?.token_hash||null,this.store.clock()+300000);const url=new URL('https://accounts.google.com/o/oauth2/v2/auth');url.search=new URLSearchParams({client_id:this.clientId,redirect_uri:this.origin+'/vpn/api/google/callback',response_type:'code',scope:'openid email profile',state:id,nonce,code_challenge:createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'S256'});return {state:id,url:url.href};}
 async finish(state,cookie,code){if(!this.ready()||!state||state!==cookie||typeof code!=='string'||code.length>4096)throw new Error('Вход Google не подтверждён');const row=this.db.prepare('SELECT * FROM google_states WHERE id=? AND expires>?').get(state,this.store.clock());if(!row)throw new Error('Запрос устарел');this.db.prepare('DELETE FROM google_states WHERE id=?').run(state);const response=await this.request('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:this.clientId,client_secret:this.secret,redirect_uri:this.origin+'/vpn/api/google/callback',grant_type:'authorization_code',code_verifier:row.verifier}),signal:AbortSignal.timeout(8000),redirect:'error'});if(!response.ok)throw new Error('Google временно недоступен');const result=await response.json(),parts=result.id_token?.split('.');if(parts?.length!==3)throw new Error('Invalid Google token');const header=JSON.parse(Buffer.from(parts[0],'base64url')),payload=JSON.parse(Buffer.from(parts[1],'base64url'));if(header.alg!=='RS256'||payload.aud!==this.clientId||!['https://accounts.google.com','accounts.google.com'].includes(payload.iss)||payload.nonce!==row.nonce||payload.exp*1000<=this.store.clock()||payload.iat*1000>this.store.clock()+60000||payload.email_verified!==true||typeof payload.sub!=='string'||typeof payload.email!=='string')throw new Error('Invalid Google identity');const keysResponse=await this.request('https://www.googleapis.com/oauth2/v3/certs',{signal:AbortSignal.timeout(8000),redirect:'error'});if(!keysResponse.ok)throw new Error('Google temporarily unavailable');const jwk=(await keysResponse.json()).keys?.find(k=>k.kid===header.kid);if(!jwk||!verify('RSA-SHA256',Buffer.from(parts[0]+'.'+parts[1]),createPublicKey({key:jwk,format:'jwk'}),Buffer.from(parts[2],'base64url')))throw new Error('Invalid Google signature');
  const linked=this.db.prepare('SELECT * FROM google_identities WHERE subject=?').get(payload.sub);let id=row.account_id||linked?.account_id;
  if(row.account_id){if(!this.db.prepare('SELECT 1 FROM sessions WHERE token_hash=? AND account_id=? AND expires>?').get(row.session_hash,id,this.store.clock())||this.users.identity(id)?.must_change||linked&&linked.account_id!==id)throw new Error('Google уже привязан к другому аккаунту');}
  if(!id){const account=await this.users.add({login:'google_'+randomBytes(10).toString('hex')});id=account.accountId;this.db.prepare('UPDATE identities SET must_change=0,password_set=0 WHERE account_id=?').run(id);}
  this.db.prepare('INSERT INTO google_identities VALUES(?,?,?) ON CONFLICT(subject) DO UPDATE SET email=excluded.email').run(payload.sub,id,payload.email);return this.users.newSession(id,{method:'google'});
 }
 state(id){return {available:this.ready(),linked:Boolean(this.db.prepare('SELECT 1 FROM google_identities WHERE account_id=?').get(id))};}
 unlink(id){if(!this.db.prepare('SELECT password_set FROM identities WHERE account_id=?').get(id)?.password_set&&!this.db.prepare('SELECT 1 FROM passkeys WHERE account_id=?').get(id))throw new Error('Сначала установи пароль или добавь ключ входа');this.db.prepare('DELETE FROM google_identities WHERE account_id=?').run(id);}
}
