import {randomBytes} from 'node:crypto';
import {generateRegistrationOptions,verifyRegistrationResponse,generateAuthenticationOptions,verifyAuthenticationResponse} from '@simplewebauthn/server';
export class Passkeys{
 constructor(store,users,origin){this.store=store;this.users=users;this.db=store.db;this.origin=origin;this.rpID=new URL(origin).hostname;this.db.exec(`CREATE TABLE IF NOT EXISTS passkeys(id TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES identities(account_id),public_key BLOB NOT NULL,counter INTEGER NOT NULL,transports TEXT NOT NULL,name TEXT NOT NULL,created_at INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS passkey_challenges(id TEXT PRIMARY KEY,account_id TEXT,session_hash TEXT REFERENCES sessions(token_hash) ON DELETE CASCADE,kind TEXT NOT NULL,challenge TEXT NOT NULL,expires INTEGER NOT NULL);`);}
 list(id){return this.db.prepare('SELECT id,name,created_at FROM passkeys WHERE account_id=?').all(id);}
 async options(session){this.db.prepare('DELETE FROM passkey_challenges WHERE expires<=?').run(this.store.clock());if(this.db.prepare('SELECT count(*) n FROM passkey_challenges').get().n>1000)throw new Error('Повтори позже');if(session&&this.list(session.account_id).length>=10)throw new Error('Лимит ключей входа');const o=session?await generateRegistrationOptions({rpName:'Family VPN',rpID:this.rpID,userName:session.identity.login,userID:Buffer.from(session.account_id),attestationType:'none',authenticatorSelection:{residentKey:'required',userVerification:'required'},excludeCredentials:this.list(session.account_id).map(p=>({id:p.id}))}):await generateAuthenticationOptions({rpID:this.rpID,userVerification:'required'});const id=randomBytes(24).toString('base64url');this.db.prepare('INSERT INTO passkey_challenges VALUES(?,?,?,?,?,?)').run(id,session?.account_id||null,session?.token_hash||null,session?'register':'login',o.challenge,this.store.clock()+300000);return {challengeId:id,options:o};}
 take(id,kind,session){const p=this.db.prepare('SELECT * FROM passkey_challenges WHERE id=? AND expires>? AND kind=?').get(id,this.store.clock(),kind);if(!p||kind==='register'&&(!session||p.session_hash!==session.token_hash||p.account_id!==session.account_id))throw new Error('Запрос входа устарел');this.db.prepare('DELETE FROM passkey_challenges WHERE id=?').run(id);return p.challenge;}
 async register(session,id,response,name){const challenge=this.take(id,'register',session),v=await verifyRegistrationResponse({response,expectedChallenge:challenge,expectedOrigin:this.origin,expectedRPID:this.rpID,requireUserVerification:true});if(!v.verified||!v.registrationInfo)throw new Error('Ключ не подтверждён');const c=v.registrationInfo.credential;this.db.prepare('INSERT INTO passkeys VALUES(?,?,?,?,?,?,?)').run(c.id,session.account_id,Buffer.from(c.publicKey),c.counter,JSON.stringify(c.transports||[]),typeof name==='string'&&name.trim()?name.trim().slice(0,80):'Ключ входа',this.store.clock());return this.list(session.account_id);}
 async login(id,response){const challenge=this.take(id,'login'),p=this.db.prepare('SELECT * FROM passkeys WHERE id=?').get(response?.id);if(!p||!this.users.identity(p.account_id)?.enabled)throw new Error('Не удалось войти');const v=await verifyAuthenticationResponse({response,expectedChallenge:challenge,expectedOrigin:this.origin,expectedRPID:this.rpID,requireUserVerification:true,credential:{id:p.id,publicKey:new Uint8Array(p.public_key),counter:p.counter,transports:JSON.parse(p.transports)}});if(!v.verified)throw new Error('Не удалось войти');const changed=this.db.prepare('UPDATE passkeys SET counter=? WHERE id=? AND counter=?').run(v.authenticationInfo.newCounter,p.id,p.counter);if(!changed.changes)throw new Error('Повтори вход');return this.users.newSession(p.account_id,{method:'passkey'});}
 remove(owner,id){if(this.list(owner).length===1&&!this.db.prepare('SELECT password_set FROM identities WHERE account_id=?').get(owner)?.password_set&&!this.db.prepare('SELECT 1 FROM google_identities WHERE account_id=?').get(owner))throw new Error('Сначала добавь другой способ входа');this.db.prepare('DELETE FROM passkeys WHERE id=? AND account_id=?').run(id,owner);}
}
