import webpush from 'web-push';
import {createHash} from 'node:crypto';
const DAY=86400000;
export class PushNotifications{
 constructor(store,{publicKey='',privateKey='',send=null}={}){this.store=store;this.db=store.db;this.publicKey=publicKey;this.privateKey=privateKey;this.send=send||((subscription,payload)=>webpush.sendNotification(subscription,payload,{TTL:3600,timeout:8000,vapidDetails:{subject:'mailto:support@family-pie.ru',publicKey,privateKey}}));this.db.exec(`CREATE TABLE IF NOT EXISTS push_subscriptions(id TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES identities(account_id),subscription TEXT NOT NULL,created_at INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS push_deliveries(id TEXT PRIMARY KEY,subscription_id TEXT NOT NULL REFERENCES push_subscriptions(id) ON DELETE CASCADE,payload TEXT NOT NULL,state TEXT NOT NULL DEFAULT 'pending',created_at INTEGER NOT NULL);`);}
 ready(){return Boolean(this.publicKey&&this.privateKey);}
 state(id){return {available:this.ready(),publicKey:this.ready()?this.publicKey:null,devices:this.db.prepare('SELECT id,created_at FROM push_subscriptions WHERE account_id=?').all(id)};}
 subscribe(id,s){if(!this.ready())throw new Error('Push ещё не подключён');const u=new URL(s?.endpoint),host=u.hostname;if(u.protocol!=='https:'||u.username||u.password||u.port||!['fcm.googleapis.com','updates.push.services.mozilla.com','web.push.apple.com'].some(h=>host===h||host.endsWith('.'+h))||s.endpoint.length>2048||typeof s.keys?.p256dh!=='string'||typeof s.keys?.auth!=='string'||Buffer.from(s.keys.p256dh,'base64url').length!==65||Buffer.from(s.keys.auth,'base64url').length!==16)throw new Error('Неверная push-подписка');const key=createHash('sha256').update(s.endpoint).digest('hex'),existing=this.db.prepare('SELECT account_id FROM push_subscriptions WHERE id=?').get(key);if(existing&&existing.account_id!==id)throw new Error('Устройство уже привязано');if(this.db.prepare('SELECT count(*) n FROM push_subscriptions WHERE account_id=?').get(id).n>=10&&!existing)throw new Error('Лимит устройств уведомлений');this.db.prepare('INSERT INTO push_subscriptions VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET subscription=excluded.subscription').run(key,id,JSON.stringify({endpoint:s.endpoint,keys:s.keys}),this.store.clock());return this.state(id);}
 disconnect(id,device){this.db.prepare('DELETE FROM push_subscriptions WHERE account_id=? AND id=?').run(id,device);}
 plan(){const now=this.store.clock();this.db.prepare("UPDATE push_deliveries SET state='uncertain' WHERE state='sending'").run();this.db.prepare("DELETE FROM push_deliveries WHERE state IN ('sent','uncertain','canceled') AND created_at<?").run(now-90*DAY);for(const s of this.db.prepare('SELECT p.*,i.enabled identity_enabled,m.*,c.news FROM push_subscriptions p JOIN identities i USING(account_id) JOIN managed_subscriptions m USING(account_id) LEFT JOIN cabinet_profiles c USING(account_id)').all()){
  if(!s.identity_enabled||s.deleted||s.unlimited||s.sync_state!=='synced'||!s.expires_at||s.expires_at<now-7*DAY||s.expires_at>now+3*DAY)continue;const stage=s.expires_at<=now?'expired':s.expires_at<=now+DAY?'one-day':'three-days',key=s.id+':'+s.expires_at+':'+stage,payload={title:'Family VPN',body:stage==='expired'?'Подписка закончилась. Открой кабинет для продления.':stage==='one-day'?'Подписка заканчивается в течение суток.':'До окончания подписки осталось не более3 дней.',tag:key};if(!s.enabled&&stage!=='expired')continue;this.db.prepare("INSERT INTO push_deliveries(id,subscription_id,payload,created_at) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET state='pending',created_at=excluded.created_at WHERE push_deliveries.state='canceled'").run(key,s.id,JSON.stringify(payload),now);
 }}
 async tick(){if(!this.ready()||this.running)return;this.running=true;try{this.plan();for(const d of this.db.prepare("SELECT d.*,p.subscription,p.account_id FROM push_deliveries d JOIN push_subscriptions p ON p.id=d.subscription_id WHERE d.state='pending' ORDER BY d.created_at LIMIT 10").all()){const s=this.db.prepare('SELECT m.*,i.enabled identity_enabled FROM managed_subscriptions m JOIN identities i USING(account_id) WHERE account_id=?').get(d.account_id),parts=d.id.split(':');if(!s?.identity_enabled||s.deleted||s.unlimited||s.sync_state!=='synced'||String(s.expires_at)!==parts[1]||s.expires_at>this.store.clock()+3*DAY||s.expires_at<this.store.clock()-7*DAY||parts[2]!==((s.expires_at-this.store.clock())<=0?'expired':s.expires_at-this.store.clock()<=DAY?'one-day':'three-days')||!s.enabled&&s.expires_at>this.store.clock()){this.db.prepare("UPDATE push_deliveries SET state='canceled' WHERE id=?").run(d.id);continue;}this.db.prepare("UPDATE push_deliveries SET state='sending' WHERE id=?").run(d.id);try{await this.send(JSON.parse(d.subscription),d.payload);this.db.prepare("UPDATE push_deliveries SET state='sent' WHERE id=?").run(d.id);}catch(e){if([403,404,410].includes(e.statusCode))this.db.prepare('DELETE FROM push_subscriptions WHERE id=?').run(d.subscription_id);else this.db.prepare('UPDATE push_deliveries SET state=? WHERE id=?').run(e.statusCode===429?'pending':'uncertain',d.id);}}}finally{this.running=false;}}
}
