import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {spawnSync} from 'node:child_process';
import {VpnStore} from '../store.mjs';import {Accounts} from '../auth.mjs';import {YooKassaReader} from '../yookassa.mjs';
const DAY=86400_000,plans=[{days:30,priceMinor:100,devices:1}],policy=new URL('../payment-access.py',import.meta.url).pathname;
function broker(path){const script=`import sqlite3,importlib.util,time\ns=importlib.util.spec_from_file_location('policy',${JSON.stringify(policy)});m=importlib.util.module_from_spec(s);s.loader.exec_module(m)\nc=sqlite3.connect(${JSON.stringify(path)});c.row_factory=sqlite3.Row;c.execute('PRAGMA foreign_keys=ON');m.reconcile(c,int(time.time()*1000))`;
 const result=spawnSync('python3',['-c',script],{encoding:'utf8'});assert.equal(result.status,0,result.stderr);}
test('account creation/admin edits cannot issue unpaid VPN access or accept browser paid flags',async t=>{
 const store=new VpnStore(':memory:',{plans});t.after(()=>store.close());const users=new Accounts(store);const admin=await users.add({login:'paid-policy-admin',role:'admin'});
 const user=await users.add({login:'unpaid-fixture',expiresAt:Date.now()+30*DAY,actor:admin.accountId});assert.equal(users.subscription(user.accountId).payment_required,true);assert.equal(users.subscription(user.accountId).active,false);assert.equal(users.subscription(user.accountId).enabled,0);assert.equal(users.subscription(user.accountId).profile_url,null);assert.equal(users.db.prepare('SELECT count(*) n FROM admin_jobs').get().n,0);
 users.edit(admin.accountId,user.accountId,{enabled:true,paid:true,payment_required:false,sync_state:'synced'});assert.equal(users.subscription(user.accountId).active,false);assert.equal(users.db.prepare('SELECT count(*) n FROM admin_jobs').get().n,0);
 const order=store.createOrder(user.accountId,30,'unpaid-fixture-order');store.bindPayment(user.accountId,order.id,'unpaid-fixture-payment');
 assert.throws(()=>store.confirmPayment({id:'unpaid-fixture-payment',paid:true,status:'pending',test:true,amount:{currency:'RUB',value:'1.00'},metadata:{order_id:order.id}}));assert.equal(users.subscription(user.accountId).active,false);
});
test('verified provider grants are bridged to physical outbox; refunds revoke, legacy access stays',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'vpn-paid-policy-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const path=join(dir,'private.sqlite');const store=new VpnStore(path,{plans});t.after(()=>store.close());const users=new Accounts(store);
 const old=await users.add({login:'old-paid-policy-fixture',panelLogin:'legacy-fixture',profileUrl:'https://example.invalid/legacy',unlimited:true,allowUnlimited:true});
 const user=await users.add({login:'paid-policy-fixture',expiresAt:Date.now()+90*DAY});broker(path);assert.equal(users.subscription(user.accountId).active,false);assert.equal(users.db.prepare('SELECT count(*) n FROM admin_jobs').get().n,0);
 const order=store.createOrder(user.accountId,30,'verified-fixture-order');store.bindPayment(user.accountId,order.id,'verified-fixture-payment');const payment={id:'verified-fixture-payment',status:'succeeded',paid:true,test:true,recipient:{account_id:'fixture-shop'},amount:{currency:'RUB',value:'1.00'},metadata:{order_id:order.id}};
 const reader=new YooKassaReader({shopId:'fixture-shop',secret:'FICTIONAL_TEST_SECRET',testMode:true,request:async()=>({ok:true,json:async()=>payment})});await reader.confirmPayment(store,payment.id);broker(path);
 const s=users.subscription(user.accountId);assert.equal(s.payment_required,false);assert.equal(s.enabled,1);assert.equal(s.sync_state,'pending');assert.equal(s.expires_at,store.subscription(user.accountId).expiresAt);assert.equal(users.db.prepare('SELECT count(*) n FROM admin_jobs').get().n,1);
 // Simulated successful physical read-back; never contacts a real VPN panel.
 users.db.prepare("UPDATE managed_subscriptions SET panel_login='web_fixture',profile_url='https://example.invalid/paid',sync_state='synced' WHERE account_id=?").run(user.accountId);broker(path);assert.equal(users.subscription(user.accountId).active,true);assert.equal(store.db.prepare('SELECT state FROM jobs WHERE account_id=?').get(user.accountId).state,'done');
 store.confirmFullRefund({id:'fixture-refund',payment_id:payment.id,status:'succeeded',amount:{currency:'RUB',value:'1.00'}});assert.equal(users.subscription(user.accountId).active,false);assert.equal(users.subscription(user.accountId).profile_url,null);broker(path);assert.equal(users.subscription(user.accountId).enabled,0);const revoke=users.db.prepare('SELECT payload FROM admin_jobs WHERE account_id=? ORDER BY id DESC LIMIT 1').get(user.accountId);assert.equal(JSON.parse(revoke.payload).enabled,false);
 assert.equal(users.subscription(old.accountId).active,true);assert.equal(users.subscription(old.accountId).profile_url,'https://example.invalid/legacy');
});
