import {test} from 'node:test';import assert from 'node:assert/strict';
import {VpnStore} from '../store.mjs';import {Accounts} from '../auth.mjs';import {Billing} from '../billing.mjs';import {PurchaseMail} from '../purchase-mail.mjs';import {smtpPurchaseSender} from '../email.mjs';
async function fixture(t){let now=1_800_000_000_000;const store=new VpnStore(':memory:',{clock:()=>now,plans:[{days:30,priceMinor:30000,devices:0}]});t.after(()=>store.close());const users=new Accounts(store);new Billing(store);const u=await users.add({login:'mail-fixture'});const id=u.accountId;store.db.prepare('UPDATE identities SET must_change=0 WHERE account_id=?').run(id);const sent=[];const mail=new PurchaseMail(store,{send:async m=>{sent.push(m);return {accepted:[m.to]};}});
 function order(key='mail-order'){const o=store.createOrder(id,30,key);store.db.prepare('UPDATE orders SET receipt_email=? WHERE id=?').run('owned@example.invalid',o.id);return o;}
 function paid(o){store.bindPayment(id,o.id,'pay-'+o.id);store.confirmPayment({id:'pay-'+o.id,status:'succeeded',paid:true,test:true,amount:{currency:'RUB',value:'300.00'},metadata:{order_id:o.id}});}
 function synced(){store.db.prepare("UPDATE managed_subscriptions SET enabled=1,sync_state='synced',expires_at=?,entitlement_revision=? WHERE account_id=?").run(store.subscription(id).expiresAt,store.account(id).revision,id);}
 return {store,users,id,mail,sent,order,paid,synced,advance:n=>now+=n};}
test('mail waits for verified payment and current successful provisioning, then deduplicates',async t=>{const f=await fixture(t),o=f.order();await f.mail.tick();assert.equal(f.sent.length,0);f.paid(o);await f.mail.tick();assert.equal(f.sent.length,0);f.synced();await Promise.all([f.mail.tick(),f.mail.tick()]);assert.equal(f.sent.length,1);assert.equal(f.sent[0].to,'owned@example.invalid');assert.equal(f.sent[0].days,30);assert.equal(f.sent[0].profileUrl,undefined);assert.equal(f.sent[0].password,undefined);await f.mail.tick();assert.equal(f.sent.length,1);assert.equal(f.store.db.prepare('SELECT state FROM purchase_mail').get().state,'sent');});
test('refund, disabled account and expired access cannot produce a ready-subscription email',async t=>{for(const mode of ['refund','disabled','expired']){const f=await fixture(t),o=f.order();f.paid(o);f.synced();f.mail.plan();if(mode==='refund')f.store.confirmFullRefund({id:'refund-fixture',payment_id:'pay-'+o.id,status:'succeeded',amount:{currency:'RUB',value:'300.00'}});if(mode==='disabled')f.store.db.prepare('UPDATE identities SET enabled=0 WHERE account_id=?').run(f.id);if(mode==='expired')f.advance(31*86400000);await f.mail.tick();assert.equal(f.sent.length,0);assert.equal(f.store.db.prepare('SELECT state FROM purchase_mail').get().state,'canceled');}});
test('an explicit pre-DATA failure retries with the same message ID; lost DATA response never blindly retries',async t=>{const f=await fixture(t),o=f.order();f.paid(o);f.synced();const ids=[];f.mail.send=async m=>{ids.push(m.messageId);throw Object.assign(new Error('synthetic'),{code:'ECONNECTION',command:'CONN'});};await f.mail.tick();assert.equal(f.store.db.prepare('SELECT state FROM purchase_mail').get().state,'pending');f.advance(60000);f.mail.send=async m=>{ids.push(m.messageId);throw Object.assign(new Error('synthetic'),{code:'ETIMEDOUT',command:'DATA'});};await f.mail.tick();assert.equal(ids.length,2);assert.equal(ids[0],ids[1]);assert.equal(f.store.db.prepare('SELECT state FROM purchase_mail').get().state,'uncertain');f.advance(3600000);await f.mail.tick();assert.equal(ids.length,2);});
test('interrupted send recovers as uncertain, and permanent recipient rejection fails without retries',async t=>{const f=await fixture(t),o=f.order();f.paid(o);f.synced();f.mail.plan();f.store.db.prepare("UPDATE purchase_mail SET state='sending'").run();f.mail.recover();await f.mail.tick();assert.equal(f.sent.length,0);assert.equal(f.store.db.prepare('SELECT state FROM purchase_mail').get().state,'uncertain');const o2=f.order('mail-second');f.paid(o2);f.synced();f.mail.send=async()=>{throw Object.assign(new Error('synthetic'),{responseCode:550,command:'RCPT TO'});};await f.mail.tick();assert.equal(f.store.db.prepare('SELECT state FROM purchase_mail WHERE order_id=?').get(o2.id).state,'failed');});
test('historical purchases require explicit backfill and graceful shutdown awaits a claimed send',async t=>{const f=await fixture(t),o=f.order();f.paid(o);f.synced();f.advance(1000);f.store.db.prepare('UPDATE purchase_mail_config SET start_at=?').run(f.store.clock());await f.mail.tick();assert.equal(f.sent.length,0);assert.equal(f.mail.enqueue(o.id),true);let release,started;const begin=new Promise(r=>started=r);f.mail.send=async m=>{started();return new Promise(r=>release=()=>r({accepted:[m.to]}));};const tick=f.mail.tick();await begin;let closed=false;const stop=f.mail.shutdown().then(()=>closed=true);await Promise.resolve();assert.equal(closed,false);release();await Promise.all([tick,stop]);assert.equal(closed,true);assert.equal(f.store.db.prepare('SELECT state FROM purchase_mail').get().state,'sent');});
test('purchase sender includes only the public cabinet link and receipt-independent subscription confirmation',async()=>{let message;const send=smtpPurchaseSender({VPN_SMTP_HOST:'smtp.example.invalid',VPN_SMTP_FROM:'sender@example.invalid'},()=>({sendMail:async m=>{message=m;return {accepted:[m.to]};}}));await send({to:'owned@example.invalid',days:30,expiresAt:1_800_000_000_000,messageId:'<synthetic@example.invalid>'});assert.equal(message.subject,'Family VPN — подписка готова');assert.equal(message.messageId,'<synthetic@example.invalid>');assert.match(message.text,/https:\/\/family-pie.ru\/vpn\/cabinet\/#home/);assert.doesNotMatch(message.text,/vless:|hysteria:|\/sub\//);assert.equal(message.attachments,undefined);});
test('explicit temporary DATA rejection retries at most five times and never fabricates acceptance',async t=>{const f=await fixture(t),o=f.order();f.paid(o);f.synced();let calls=0;f.mail.send=async()=>{calls++;throw Object.assign(new Error('synthetic rejection'),{responseCode:451,command:'DATA'});};for(let n=0;n<5;n++){await f.mail.tick();f.advance(3600000);}assert.equal(calls,5);assert.equal(f.store.db.prepare('SELECT state FROM purchase_mail').get().state,'failed');await f.mail.tick();assert.equal(calls,5);const other=f.order('no-accepted-recipient');f.paid(other);f.synced();f.mail.send=async()=>({accepted:[],rejected:['owned@example.invalid']});await f.mail.tick();assert.equal(f.store.db.prepare('SELECT state FROM purchase_mail WHERE order_id=?').get(other.id).state,'failed');});
